# Generated by Django 5.2.1 on 2025-05-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('last_cached', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
